# Generated by Django 5.2.8 on 2026-02-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
