# Generated by Django 5.2.8 on 2026-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_purchaseorder_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
