# Generated by Django 6.0 on 2026-01-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='display_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid'), ('READY', 'Ready'), ('CANCELED', 'Canceled')], default='OPEN', max_length=10),
        ),
    ]
