# Generated by Django 6.0 on 2026-01-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ready',
        ),
    ]
