# Generated by Django 6.0 on 2026-01-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_orderitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='description',
            new_name='detail',
        ),
    ]
