# Generated by Django 6.0 on 2026-01-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_description_orderitem_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text="Colors: ['#e74c3c', '#3498db']"),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text="Colors: ['#e74c3c', '#3498db']"),
        ),
    ]
