# Generated by Django 5.2.8 on 2026-01-08 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_category_colors_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='inkassa',
            name='inkass_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UZCARD', 'Uzcard'), ('HUMOHumo', 'Humo'), ('PAYMEPayme', 'Payme')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
