# Generated by Django 5.2.8 on 2026-01-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_inkassa_inkass_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
